/**
 * API layer index. Import services from here or from lib/api/<module>.
 */

export { apiRequest } from "./client"
export type { ApiError } from "./client"
export { postTelegramAuth, getMe } from "./auth"
export type { TelegramAuthPayload, TelegramAuthResponse } from "./auth"
export { getDashboardStats } from "./dashboard"
export type { DashboardStats } from "./dashboard"
export { getClients, createClient } from "./clients"
export type { ClientDto } from "./clients"
export { getProducts } from "./products"
export type { ProductDto } from "./products"
export { getDebts } from "./debts"
export type { DebtDto } from "./debts"
export { getInvoices } from "./invoices"
export type { InvoiceDto, InvoiceItemDto } from "./invoices"
export { getReportSummary } from "./reports"
export type { ReportSummaryDto } from "./reports"
export { getApprentices } from "./apprentices"
export type { ApprenticeDto } from "./apprentices"
export { getExpenses } from "./expenses"
export type { ExpenseDto } from "./expenses"
export { getPriceGroups } from "./prices"
export type { PriceGroupDto } from "./prices"
export { getCashTransactions } from "./cash"
export type { CashTransactionDto } from "./cash"
